[THIRDCOAST.SWERVE]
  length        = 20.5   # wheelbase length
  width         = 26.625 # wheelbase width
  enableGyroLogging = true # turn this off if too noisy

[THIRDCOAST.TALONS]
  summarizeErrors = true

[[TALON]]
  name = "azimuth"
  talonIds = [0, 1, 2, 3]
  [TALON.selectedFeedbackSensor]
    feedbackDevice = "CTRE_MagEncoder_Relative"
  [TALON.currentLimit]
    continuous = 10
    peak = 0
    peakDuration = 0
  [TALON.motionMagic]
    acceleration = 10_000
    cruiseVelocity = 800
  [[TALON.closedLoopProfile]] # slot 0 MotionMagic, normal
    pGain = 10.0
    iGain = 0.0
    dGain = 100.0
    fGain = 1.0
    iZone = 0
    allowableClosedLoopError = 0

[[TALON]]
 name = "drive"
 talonIds = [10, 11, 12, 13]
 [TALON.selectedFeedbackSensor]
   feedbackDevice = "CTRE_MagEncoder_Relative"
 [TALON.output]
   neutralMode = "Brake"
 [TALON.currentLimit]
   continuous = 40
   peak = 0
   peakDuration = 0
 [TALON.velocityMeasurement]
   period = "Period_50Ms"
   window = 32
